config/routes.rb
ULSafety::Application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'login'=>'login#index'
  get 'avatars'=>'avatars#index' 
  
  post 'login'=>'login#create'
  post'avatars'=>'avatars#create'
  
  get 'interactive_lab'=>'interactive_lab#index'
  post 'interactive_lab'=>'interactive_lab#index'

  get 'virtual_project'=>'virtual_project#index'
  post'virtual_project'=>'virtual_project#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters_for_devise, if: :devise_controller?
  
  def after_sign_in_path_for (resource_or_scope)
  	interactive_lab_path
  end

  protected

  def configure_permitted_parameters_for_devise
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:sign_up) << :age
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
	def index
	end
	def create 
		redirect_to'/'
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @random_number = rand(30)
  end
end

app/controllers/interactive_lab_controller.rb
class InteractiveLabController < ApplicationController

  def index
    
  end

end

app/controllers/login_controller.rb
class LoginController <ApplicationController
	def index
	end

	def create 
		redirect_to'/interactive_lab'
	end
end

app/controllers/virtual_project_controller.rb
class VirtualProjectController < ApplicationController
	def index
	end

	def create 
		redirect_to'/virtualproject'
	end
end

app/controllers/virtualproject_controller.rb
class VirtualProject <ApplicationController
	def index
	end

	def create 
		redirect_to'/virtualproject'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/avatars/avatar.html.erb
  <html>
<head>
  <header align='center'><font face="drawing guides" color="white" size="20"><br align="center">Choose Your Avatar!</br></font>
  
    <style type="text/css">
    body{background:url('/assets/backgrndpic.jpg')no-repeat;background-position:center;}
    </style>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
   </script> 

 <script>
 $(document).ready(function(){
 $("#hide").click(function(){
   $("").hide();
 });
 $("#show").click(function(){
   $("").show();
 });
});

function fade_in(){
$().fadeIn
}
 </script>
   <style>     

  

    </style>

 
</head>

 <body>
    
<div style='position:absolute; left:350px; top: 250px;'><button onclick="showContinueButton(dog)" ><img width="80px"id="dog"src="/assets/dog.jpg" ></div>
<div style='position:absolute; left:650px; top: 250px;'><button onclick= "showContinueButton(cat)"><img width="80px"id="cat"src="/assets/cat.jpg"></div>
<div style='position:absolute; left:950px; top: 250px;'><button  onclick= "showContinueButton(frog)"><img width="80px"id="frog"src="/assets/frog.jpg"></div>



<div style="position:absolute;left:850px;top:450px;">
<br><button style="opacity:.4" onclick="fadeIn">CONTINUE</button></br>
</div>




    

 </body>



</html>

app/views/avatars/index.html.erb
<html>
<head>
  <script>
    function showContinueButton(avatar){
      
    }

  </script>
    <style>     
     button{
       background-image:url('assets/backgrndpic.jpg');
      
      position:absolute;
      left:90px;
      top:100px;
     }
     </style>  
</head>

  <body>

    <%= form_tag("/avatars",method:"post") do%>

  
      <br>
      <%= image_tag('dog.jpg')%>
      <img width="75px"id="dog"src="C:/Users/Stacey J/ULSafety/app/assets/images/dog.jpg" onclick= "showContinueButton(dog)"></br>
      <%= image_tag('cat.jpg') %>
      <br><img width="75px"id="cat"src="C:/Users/Stacey J/ULSafety/app/assets/images/cat.jpg" onclick= "showContinueButton(cat)"></br>
      <%= image_tag('frog.jpg') %>
      <br><img width="75px"id="frog"src="C:/Users/Stacey J/ULSafety/app/assets/images/frog.jpg" onclick= "showContinueButton(frog)"></br>
      <div style="position:absolute;left:250px;top:350px;">
      <br><input type= "submit" value = "continue">
      </div>
    <% end %>   
  </body>

</html>


app/views/interactive_lab/index.html.erb
<html>
<head>

<style>
  body{
   
  background-image:url('/assets/bluelab.jpg');  
  background-size: 1365px 665px;
  background-repeat:no-repeat;
  background-attachment:fixed;
  background-position:center; 
}

  button{
    background-color: red;
    border-style:dashed;

  }
  .categoryicon{height: 50px; width: 50px;}
  #scienceIcons{top:450px; left:100px; position:fixed;}

  
  #pamoeba {height: 200px; width:200px; position:fixed; left:1100px;top:450px}

</style>

<script type="text/javascript">
  function IconSlideUp (selector){

    $(selector).animate({top: "+=50px"}, IconSlideDown(selector));
  }
  function IconSlideDown(selector){

    $(selector).animate({top: "-=50px"});
  }

  function IconSlideUpMove (selector){

    $(selector).animate({top: "+=50px", width:"+=20px"}, IconSlideDownMove(selector));
  }
  function IconSlideDownMove(selector){

    $(selector).animate({top: "-=50px", width:"-=20px"});
  }

  $(document).ready(function(){
    var bounceInterval = setInterval(function(){ IconSlideUp('#scienceIcons')}, 1000);
    var bounceInterval = setInterval(function(){ IconSlideUpMove('#pamoeba')}, -1000);

  });

</script>

</head>
  
  <body>

    <div style="position:fixed;left:1200px;top:100px">
      <button onclick="alert('Press OK to go Home or X to cancel');"><font color="white" size="5";> HOME </font></button>
    </div> 

    <div style="position:fixed;left:160px;top:525px">
      <%= link_to "SELECT A SCIENCE", virtual_project_path, :confirm => 'Are you sure you want to select a science?', :style => "color:  white; background-color: red; border-style: dotted; font-size: 1.2em; padding: 3px;" %>
    </div>

    <div style="position:fixed;left:432px;top:160px"> 
      <button onclick="alert('Press OK to go to Parents Corner or X to cancel');"><font color="white" size="3";> PARENT'S CORNER </font></button>
    </div>

    <div>
     <img src="/assets/purpleamoeba.png" class="categoryicon" id="pamoeba"/>
    </div>

    <div style="position: fixed; left:420px; top:165px">
      <img width="195px" height="130px" src="/assets/ulsign1.png"/>
    </div>

    <div id="scienceIcons">
      <img src= "/assets/electricicon.png" class="categoryicon"/>
      <img src= "/assets/flameicon.png" class="categoryicon"/>
      <img src= "/assets/waterdrop.png" class="categoryicon" />
    </div>
  </body>
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ULSafety</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<% if user_signed_in? %>
		<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
	<% end %>
	<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<html>
	<head>


		<header align='center'><font face="drawing guides" color="white" size="20"><br align="center">Welcome!</br></font>

			<font face="drawing guides" color="white" size="5"><br>You're on your way to becoming a Junior Scientist!</br></font>

			<style type="text/css">
          body{background:url('C:/Users/Tiffani/ULSafety/app/assets/images/backgrndpic.jpg')no-repeat;background-position:center;}
          </style>
	</head>
		<br></br>
		<body>

		<%= form_tag("/login",method:"post") do %>

			<table align='center'>
			<tr>
			<td align="right"><font face="drawing guides" color="white" size="5">Child's Name:</font></td>
			<td align="left"><input placeholder= "enter name"/></td>
			</tr>

			<tr>
			<td align="right"><font face="drawing guides" color="white" size="5">Child's Age:</font></td>
			<td align="left"><input type=numbers placeholder= "enter age" maxlength='2'onkeypress='return onlyNumbers();'/></td>
			</tr>

			<tr>
			<td align="right"><font face="drawing guides" color="white" size="5">Your Email:</td></font>
			<td align="left"><input placeholder="enter email address"/></td>
			</tr>

			<tr>

			<td align="right"><font face="drawing guides" color="white" size="5">Create Pincode</font></td>
			<td align="left"><input type= "password" onkeypress="return onlyNumbers();" placeholder= "enter pincode" maxlength="4"/></td>
			</tr>

			<tr>
			<td align="right"><button type="submit">Submit</button>

</table>
<% end %>

<script language="JavaScript">
function onlyNumbers(evt)
{
  var e = event || evt; // for trans-browser compatibility
  var charCode = e.which || e.keyCode;

  if (charCode > 31 && (charCode < 48 || charCode > 57))
    return false;

  return true;

}
</script>

app/views/virtual_project/materials.html.erb
<html>
		<head>
			<meta charset="utf-8">
			<script src="http://code.jquery.com/jquery-1.8.3.js"> </script>

			<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
			<script src="htt//code.jquery.com/jquery-1.91.js"></script>
			<script src="http//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
			<link rel="stylesheet"href="/resources/demos/style.css">

			<script>
				$(function(){
					$("#dishsoap").draggable();
					$("#foodcolor").draggable();
					$("#dishsoap").draggable();
					$("#dishsoap").draggable();
				});

			</script>

			<style>

				body{
   
					  background-image:url('image1/materialbackground.jpg');  
					  background-size: 1365px 665px;
					  background-repeat:no-repeat;
					  background-attachment:fixed;
					  background-position:center; 
					}
				#dishsoap
				{
					position: absolute;
					left:325px;
					top:310px;
				}
				#foodcolor
				{
					position: absolute;
					left:425px;
					top:310px;
				}
				#peroxide
				{
					position: absolute;
					left:325px;
					top:410px;
				}
				#wateryeast
				{
					position: absolute;
					left:425px;
					top:410px;
				}
				#shelf
				{
					position: absolute;
					left:250px;
					top:260px;
					width:300px;
					height:400px;
				}
				#verticalshelf
				{
					position: absolute;
					left:800px;
					top:300px;
					width:275px;
					height:350px;
				}


			</style>
				
		</head> 	
	<body>

			<img  id="shelf" src="image1/shelf.png"/>
			<img  id="verticalshelf" src="image1/verticalshelf.jpg"/>
			<img width="50px" id="dishsoap" src="image1/dishsoap.jpg"/>
			<img width="50px" id="foodcolor" src="image1/foodcolor.jpg"/>
			<img width="50px" id="peroxide" src="image1/peroxide.jpg"/>
			<img width="50px" id="wateryeast" src="image1/wateryeast.jpg"/>
			





<!--buttons-->
		<button onclick="alert('hello world');">
			Hello World!!!
		</button> 
			<button onclick="speak_hello_world();">
				Hello World!!!
			</button> 
				<button onclick="square();">
					Square
				</button>
					<button onclick="triangle();">
						Triangle
					</button>
						<button onclick="dimond();">
							Dimond
						</button>
							<button onclick="bounce();">
								Bounce
							</button>
								<button onclick="move_up(10);">
									move up 10
								</button>
									<button onclick="make_x(1);">
										make x
									</button>
<!--table-->
			<table border="6px"> 
			<tr>
				<td><button onclick="move_up_left(10);">up left</button></td>
				<td><button onclick="move_up(10);">move up</button></td>
				<td><button onclick="move_up_right(10);">up right</button></td>
				
			</tr>

			<tr>
				<td><button onclick="move_left(10);">move left</button></td>
				<td></td>
				<td><button onclick="move_right(10);">move right</button></td> 
			</tr>

			<tr>
				<td><button onclick="move_down_left(10);">down left</button></td>
				<td><button onclick="move_down(10);">move down</button></td>
				<td><button onclick="move_down_right(10);">down right</button></td>
			</tr>
										
			</table>
<!--red ball image-->		

	</body>
		<script>
			function AnimationObject(cssid)
		{
			this.fade_out=function()
			{
				$(cssid).fadeOut(1000);
			}
			this.fade_in=function()
			{
				$(cssid).fadeIn(1000);
			}
			this.move=function(dx,dy){
				console.log("distance across:"+dx);
				console.log("distance up,down:"+dy); 
				var offset=$(cssid).offset();
				offset.left=offset.left+dx;
				offset.top=offset.top+dy;
				$(cssid).css({top:offset.top+'px',left:offset.left+'px'});
			}
		
		}	
		function move_downleft(){
			dishsoap.top=dishsoap.top+10
			dishsoap.left=dishsoap.left-10
		}
		function move_downright(){
			redball.top=redball.top+10
			redball.left=redball.left+10
		}
		function move_upright(){
			redball.top=redball.top-10
			redball.left=redball.left+10
		}
		function move_upleft(){
			redball.top=redball.top-10
			redball.left=redball.left-10
		}
		$(document).ready(function()
			{
				redballobj=new AnimationObject("#redball");
				console.log("document ready ran");
				greenballobj=new AnimationObject("#greenball");
			});

		</script>
</html>